services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: employee-api
    ports:
      - "8000:9000"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    networks:
      - instel

networks:
  instel:
    external: true